<a href="https://colab.research.google.com/github/camilacruz-cs/python-para-inovacao-civica/blob/main/semana2_desafio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Limpeza de dados e estatística descritiva

Neste desafio colocaremos em prática alguns conceitos apresentado nas aulas. Para isso, usaremos o conjunto de dados [Prestação de contas eleitorais - 2020](https://dadosabertos.tse.jus.br/dataset/prestacao-de-contas-eleitorais-2020) disponível no Portal de Dados Abertos do Tribunal Superior Eleitoral.

Os dados também podem ser encontrados na pasta "Dados" deste repositório.

Preencha as lacunas abaixo para completar o desafio.

# Importe os pacotes necessários

In [1]:
import pandas as pd
import numpy as np
#Correção, não adicionei a biblioteca matplot
import matplotlib.pyplot as plt

# Leia o arquivo "receitas_orgaos_partidarios_2020_NORTE.csv" que está na pasta dados desse repositório, usando o Pandas

Na aula `1.10 - Outliers e valores faltantes`, vimos como utilizar o método `replace` para substituir valores em certos colunas do nosso dataframe e trocar o texto (string) `#NULO#` pela representação padrão do Pandas para valores nulos.

Aqui, vamos utilizar um outro método, onde definimos quais strings serão considerados valores nulos já na importação do arquivo.

Edite as células abaixo e inclua:

* O nome do arquivo que queremos importar
* O separador utilizado
* Insira uma lista no parâmetro `na_values` que contenha o texto a ser ignorado.

Experimente rodar os comandos primeiro sem e depois com o parâmetro `na_values`, então, compare a diferença. Observe, por exemplo, o campo `CD_CNAE_DOADOR`.

In [2]:
df_receita = pd.read_csv('/content/receitas_orgaos_partidarios_2020_NORTE.csv', sep=';')

df_receita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6052 entries, 0 to 6051
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DT_GERACAO                   6052 non-null   object
 1   HH_GERACAO                   6052 non-null   object
 2   ANO_ELEICAO                  6052 non-null   int64
 3   CD_TIPO_ELEICAO              6052 non-null   int64
 4   NM_TIPO_ELEICAO              6052 non-null   object
 5   TP_PRESTACAO_CONTAS          6052 non-null   object
 6   DT_PRESTACAO_CONTAS          6052 non-null   object
 7   SQ_PRESTADOR_CONTAS          6052 non-null   int64
 8   CD_ESFERA_PARTIDARIA         6052 non-null   object
 9   DS_ESFERA_PARTIDARIA         6052 non-null   object
 10  SG_UF                        6052 non-null   object
 11  CD_MUNICIPIO                 5043 non-null   float64
 12  NM_MUNICIPIO                 5043 non-null   object
 13  NR_CNPJ_PRESTADOR_CONTA      6052 non-null   int64
 14  NR_PARTIDO                   6052 non-null   int64
 15  SG_PARTIDO                   6052 non-null   object
 16  NM_PARTIDO                   6052 non-null   object
 17  CD_FONTE_RECEITA             6052 non-null   int64
 18  DS_FONTE_RECEITA             6052 non-null   object
 19  CD_ORIGEM_RECEITA            6052 non-null   int64
 20  DS_ORIGEM_RECEITA            6052 non-null   object
 21  CD_NATUREZA_RECEITA          6052 non-null   int64
 22  DS_NATUREZA_RECEITA          6052 non-null   object
 23  CD_ESPECIE_RECEITA           6052 non-null   int64
 24  DS_ESPECIE_RECEITA           6052 non-null   object
 25  CD_CNAE_DOADOR               3033 non-null   float64
 26  DS_CNAE_DOADOR               3033 non-null   object
 27  NR_CPF_CNPJ_DOADOR           6016 non-null   float64
 28  NM_DOADOR                    6016 non-null   object
 29  NM_DOADOR_RFB                6016 non-null   object
 30  CD_ESFERA_PARTIDARIA_DOADOR  2071 non-null   object
 31  DS_ESFERA_PARTIDARIA_DOADOR  2071 non-null   object
 32  SG_UF_DOADOR                 3033 non-null   object
 33  CD_MUNICIPIO_DOADOR          1092 non-null   float64
 34  NM_MUNICIPIO_DOADOR          1092 non-null   object
 35  SQ_CANDIDATO_DOADOR          886 non-null    float64
 36  NR_CANDIDATO_DOADOR          962 non-null    float64
 37  CD_CARGO_CANDIDATO_DOADOR    962 non-null    float64
 38  DS_CARGO_CANDIDATO_DOADOR    962 non-null    object
 39  NR_PARTIDO_DOADOR            3033 non-null   float64
 40  SG_PARTIDO_DOADOR            3033 non-null   object
 41  NM_PARTIDO_DOADOR            3033 non-null   object
 42  NR_RECIBO_DOACAO             5623 non-null   object
 43  NR_DOCUMENTO_DOACAO          3924 non-null   object
 44  SQ_RECEITA                   6052 non-null   int64
 45  DT_RECEITA                   6052 non-null   object
 46  DS_RECEITA                   1933 non-null   object
 47  VR_RECEITA                   6052 non-null   object
dtypes: float64(8), int64(10), object(30)
memory usage: 2.2+ MB

In [3]:
df = pd.read_csv('/content/receitas_orgaos_partidarios_2020_NORTE.csv',sep=';',na_values= '#NULO')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6052 entries, 0 to 6051
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DT_GERACAO                   6052 non-null   object
 1   HH_GERACAO                   6052 non-null   object
 2   ANO_ELEICAO                  6052 non-null   int64
 3   CD_TIPO_ELEICAO              6052 non-null   int64
 4   NM_TIPO_ELEICAO              6052 non-null   object
 5   TP_PRESTACAO_CONTAS          6052 non-null   object
 6   DT_PRESTACAO_CONTAS          6052 non-null   object
 7   SQ_PRESTADOR_CONTAS          6052 non-null   int64
 8   CD_ESFERA_PARTIDARIA         6052 non-null   object
 9   DS_ESFERA_PARTIDARIA         6052 non-null   object
 10  SG_UF                        6052 non-null   object
 11  CD_MUNICIPIO                 5043 non-null   float64
 12  NM_MUNICIPIO                 5043 non-null   object
 13  NR_CNPJ_PRESTADOR_CONTA      6052 non-null   int64
 14  NR_PARTIDO                   6052 non-null   int64
 15  SG_PARTIDO                   6052 non-null   object
 16  NM_PARTIDO                   6052 non-null   object
 17  CD_FONTE_RECEITA             6052 non-null   int64
 18  DS_FONTE_RECEITA             6052 non-null   object
 19  CD_ORIGEM_RECEITA            6052 non-null   int64
 20  DS_ORIGEM_RECEITA            6052 non-null   object
 21  CD_NATUREZA_RECEITA          6052 non-null   int64
 22  DS_NATUREZA_RECEITA          6052 non-null   object
 23  CD_ESPECIE_RECEITA           6052 non-null   int64
 24  DS_ESPECIE_RECEITA           6052 non-null   object
 25  CD_CNAE_DOADOR               3033 non-null   float64
 26  DS_CNAE_DOADOR               3033 non-null   object
 27  NR_CPF_CNPJ_DOADOR           6016 non-null   float64
 28  NM_DOADOR                    6016 non-null   object
 29  NM_DOADOR_RFB                6016 non-null   object
 30  CD_ESFERA_PARTIDARIA_DOADOR  2071 non-null   object
 31  DS_ESFERA_PARTIDARIA_DOADOR  2071 non-null   object
 32  SG_UF_DOADOR                 3033 non-null   object
 33  CD_MUNICIPIO_DOADOR          1092 non-null   float64
 34  NM_MUNICIPIO_DOADOR          1092 non-null   object
 35  SQ_CANDIDATO_DOADOR          886 non-null    float64
 36  NR_CANDIDATO_DOADOR          962 non-null    float64
 37  CD_CARGO_CANDIDATO_DOADOR    962 non-null    float64
 38  DS_CARGO_CANDIDATO_DOADOR    962 non-null    object
 39  NR_PARTIDO_DOADOR            3033 non-null   float64
 40  SG_PARTIDO_DOADOR            3033 non-null   object
 41  NM_PARTIDO_DOADOR            3033 non-null   object
 42  NR_RECIBO_DOACAO             5623 non-null   object
 43  NR_DOCUMENTO_DOACAO          3924 non-null   object
 44  SQ_RECEITA                   6052 non-null   int64
 45  DT_RECEITA                   6052 non-null   object
 46  DS_RECEITA                   1933 non-null   object
 47  VR_RECEITA                   6052 non-null   object
dtypes: float64(8), int64(10), object(30)
memory usage: 2.2+ MB

# Filtre apenas os registros que sejam da prestação de contas final

In [24]:
# Primeiro vamos ver os valores únicos da coluna TP_PRESTACAO_CONTAS

df['TP_PRESTACAO_CONTAS'].unique()

array(['Final', 'Parcial', 'Relatório Financeiro',
       'Regularização da Omissão'], dtype=object)

In [25]:
# O resultado deste comando nos diz que quantas linhas e colunas temos antes do filtro
df.shape

(6052, 48)

In [6]:
# Preencha o campo os espaços abaixo com o nome da coluna e o valor desejado para nosso filtro
df_final = df[df['TP_PRESTACAO_CONTAS'] == 'Final'].copy()

In [26]:
# Rode o comando shape no novo dataframe criado e confira se o número de linhas foi reduzido

df_final.shape

(5912, 49)

In [27]:
df_final.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,TP_PRESTACAO_CONTAS,DT_PRESTACAO_CONTAS,SQ_PRESTADOR_CONTAS,CD_ESFERA_PARTIDARIA,DS_ESFERA_PARTIDARIA,...,NR_PARTIDO_DOADOR,SG_PARTIDO_DOADOR,NM_PARTIDO_DOADOR,NR_RECIBO_DOACAO,NR_DOCUMENTO_DOACAO,SQ_RECEITA,DT_RECEITA,DS_RECEITA,VR_RECEITA,TIPO_DOADOR
0,13/05/2023,23:23:30,2020,2,Ordinária,Final,25/12/2020,2021442465,M,Municipal,...,15.0,MDB,Movimento Democrático Brasileiro,P15000406050AP000001A,NaN,19516003,19/10/2020,PRESTAÇÃO DE SERVIÇO DE ASSESSORIA CONTABIL E ...,"1000,00",juridica
1,13/05/2023,23:23:30,2020,2,Ordinária,Final,29/09/2021,2021442455,M,Municipal,...,10.0,REPUBLICANOS,REPUBLICANOS,P10000406050AP000001A,850004,20034477,21/12/2020,NaN,"36,00",juridica
2,13/05/2023,23:23:30,2020,2,Ordinária,Final,14/05/2021,2021442514,M,Municipal,...,25.0,DEM,Democratas,P90000406050AP000010A,NaN,19877474,05/10/2020,PRODUÇÃO E INSERCAO PARA RADIO E TV,"15000,00",juridica
3,13/05/2023,23:23:30,2020,2,Ordinária,Final,25/12/2020,2021442465,M,Municipal,...,15.0,MDB,Movimento Democrático Brasileiro,P15000406050AP000002A,614544000054449,19516004,14/11/2020,NaN,"210000,00",juridica
4,13/05/2023,23:23:30,2020,2,Ordinária,Final,24/12/2020,2021442457,M,Municipal,...,11.0,PP,PROGRESSISTAS,P11000406050AP000001A,00000887169000105,19515403,14/10/2020,NaN,"482400,00",juridica

## Qual foi a maior doação de pessoa física e pessoa jurídica em cada estado?

Vamos usar o método `value_counts` para não só listar cada valor único da coluna `CD_CNAE_DOADOR`, como também mostrar quantos registros temos em cada um.

In [28]:
# Preencha o nome da coluna abaixo
df_final['CD_CNAE_DOADOR'].value_counts()

94928.0    2957
47814.0       2
59120.0       1
85996.0       1
Name: CD_CNAE_DOADOR, dtype: int64

In [31]:
import pandas as pd

In [9]:
# Para ver os resultados em percentuais é fácil! Basta falarmos para o value_counts que queremos os resultados normalizados
df_final['CD_CNAE_DOADOR'].value_counts(normalize=True)

94928.0    0.998649
47814.0    0.000675
59120.0    0.000338
85996.0    0.000338
Name: CD_CNAE_DOADOR, dtype: float64

Se o doador for pessoa jurídica, temos seu respectivo código CNAE. Se for pessoa física, então temos o valor `-1`.

Qual conclusão podemos tirar a respeito dos comandos acima?

Escreva um **comentário** na célula abaixo com a resposta.

In [10]:
# Mais da metade dos registros são de pessoas juridicas, com o valor de 2957 pessoas.

Agora, vamos duplicar a coluna `CD_CNAE_DOADOR` e deixar esta nova coluna apenas com 2 categorias: física (representada pelo valor -1) ou jurídica (que vamos representar inicialmente com 1).

In [41]:
# Vamos criar uma nova coluna que seja uma cópia exata da coluna CD_CNAE_DOADOR
df_final['TIPO_DOADOR'] = df_final.loc[:,'CD_CNAE_DOADOR']

#Correção, no meu, eu não coloquei o loc

In [42]:
#Correção. Não havia colocado.
df_final['TIPO_DOADOR'] = df_final.loc[:, 'CD_CNAE_DOADOR'].replace(np.nan, -1)

In [43]:
df_final.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,TP_PRESTACAO_CONTAS,DT_PRESTACAO_CONTAS,SQ_PRESTADOR_CONTAS,CD_ESFERA_PARTIDARIA,DS_ESFERA_PARTIDARIA,...,NR_PARTIDO_DOADOR,SG_PARTIDO_DOADOR,NM_PARTIDO_DOADOR,NR_RECIBO_DOACAO,NR_DOCUMENTO_DOACAO,SQ_RECEITA,DT_RECEITA,DS_RECEITA,VR_RECEITA,TIPO_DOADOR
0,13/05/2023,23:23:30,2020,2,Ordinária,Final,25/12/2020,2021442465,M,Municipal,...,15.0,MDB,Movimento Democrático Brasileiro,P15000406050AP000001A,NaN,19516003,19/10/2020,PRESTAÇÃO DE SERVIÇO DE ASSESSORIA CONTABIL E ...,"1000,00",94928.0
1,13/05/2023,23:23:30,2020,2,Ordinária,Final,29/09/2021,2021442455,M,Municipal,...,10.0,REPUBLICANOS,REPUBLICANOS,P10000406050AP000001A,850004,20034477,21/12/2020,NaN,"36,00",94928.0
2,13/05/2023,23:23:30,2020,2,Ordinária,Final,14/05/2021,2021442514,M,Municipal,...,25.0,DEM,Democratas,P90000406050AP000010A,NaN,19877474,05/10/2020,PRODUÇÃO E INSERCAO PARA RADIO E TV,"15000,00",94928.0
3,13/05/2023,23:23:30,2020,2,Ordinária,Final,25/12/2020,2021442465,M,Municipal,...,15.0,MDB,Movimento Democrático Brasileiro,P15000406050AP000002A,614544000054449,19516004,14/11/2020,NaN,"210000,00",94928.0
4,13/05/2023,23:23:30,2020,2,Ordinária,Final,24/12/2020,2021442457,M,Municipal,...,11.0,PP,PROGRESSISTAS,P11000406050AP000001A,00000887169000105,19515403,14/10/2020,NaN,"482400,00",94928.0

## Substituição condicional (conditional replacing)

Agora, vamos usar o método where do pacote NumPy (carinhosamente chamado de np abaixo).

Esta função recebe três parâmetros:

* Uma condição: no nosso caso, queremos que filtrar as coluna do CNAE onde os valores sejam -1
* Um valor: caso a condição acima seja verdadeira, qual valor deverá ser retornado?
* Outro valor: se a condição for falsa, então, qual outro valor deverá ser retornado?

In [44]:
df_final['TIPO_DOADOR'] = np.where(df_final['CD_CNAE_DOADOR']==-1, 'fisica', 'juridica')

In [45]:
df_final.tail()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,TP_PRESTACAO_CONTAS,DT_PRESTACAO_CONTAS,SQ_PRESTADOR_CONTAS,CD_ESFERA_PARTIDARIA,DS_ESFERA_PARTIDARIA,...,NR_PARTIDO_DOADOR,SG_PARTIDO_DOADOR,NM_PARTIDO_DOADOR,NR_RECIBO_DOACAO,NR_DOCUMENTO_DOACAO,SQ_RECEITA,DT_RECEITA,DS_RECEITA,VR_RECEITA,TIPO_DOADOR
6047,13/05/2023,23:23:30,2020,2,Ordinária,Final,10/12/2020,1249052678,M,Municipal,...,65.0,PC do B,Partido Comunista do Brasil,P65000401023AC000001A,NaN,17814394,28/10/2020,PRESTAÇÃO DE SERVIÇOS DE CONTABILIDADE PARA PR...,"370,00",juridica
6048,13/05/2023,23:23:30,2020,2,Ordinária,Final,07/12/2020,1421049772,M,Municipal,...,65.0,PC do B,Partido Comunista do Brasil,P65000401082AC000001A,NaN,17434268,28/10/2020,PRESTAÇÃO DE SERVIÇOS DE CONTABILIDADE PARA PR...,"37,00",juridica
6049,13/05/2023,23:23:30,2020,2,Ordinária,Final,10/11/2021,1400324204,M,Municipal,...,10.0,REPUBLICANOS,REPUBLICANOS,P10000401023AC000001A,NaN,20063362,05/11/2020,HONORÁRIOS ADVOCATÍCIOS,"800,00",juridica
6050,13/05/2023,23:23:30,2020,2,Ordinária,Final,10/12/2020,1249052678,M,Municipal,...,65.0,PC do B,Partido Comunista do Brasil,P65000401023AC000002A,NaN,17814395,12/11/2020,PRESTAÇÃO DE SERVIÇOS ADVOCATÍCIOS,"265,00",juridica
6051,13/05/2023,23:23:30,2020,2,Ordinária,Final,07/12/2020,1421049772,M,Municipal,...,65.0,PC do B,Partido Comunista do Brasil,P65000401082AC000002A,NaN,17434269,12/11/2020,PRESTAÇÃO DE SERVIÇOS ADVOCATÍCIOS,"265,00",juridica

## Agrupando (group by)

In [62]:
#Correção. Não fiz essa etapa.

df_final['VR_RECEITA'] = df_final['VR_RECEITA'].replace(',', '.')

In [ ]:
#Correção. Não fiz essa etapa.

df_final['VR_RECEITA'] = df_final['VR_RECEITA'].astype(float)

In [59]:
# Preencha abaixo primeiro uma lista com as 3 colunas que precisamos utilizar para responder à pergunta. E depois o nome das 2 colunas que precisamos agrupar.

df_final[['TIPO_DOADOR','SG_UF','VR_RECEITA']].groupby(by=['TIPO_DOADOR','SG_UF']).max()

                  VR_RECEITA
TIPO_DOADOR SG_UF
juridica    AC        960,00
            AM         99,30
            AP        986,00
            PA       9900,00
            RO       9502,40
            RR        970,00
            TO        995,94

In [64]:
# Para repetir o valor da coluna TIPO_DOADOR nas linhas, coloque o parâmetro as_index=False no método groupby do comando acima

df_final[['TIPO_DOADOR', 'CD_CNAE_DOADOR', 'TP_PRESTACAO_CONTAS']].groupby(by='TP_PRESTACAO_CONTAS', as_index=False).max()

  TP_PRESTACAO_CONTAS TIPO_DOADOR  CD_CNAE_DOADOR
0               Final    juridica         94928.0

## Qual o total de doações recebidas por partido?

In [66]:
total_doacoes = df_final[['SG_PARTIDO','NM_PARTIDO','VR_RECEITA']].groupby(by=['SG_PARTIDO','NM_PARTIDO']).sum()
total_doacoes

                                                                                               VR_RECEITA
SG_PARTIDO    NM_PARTIDO
AVANTE        AVANTE                                    15000,00500,00750,00750,00500,001,205000,00500...
CIDADANIA     Cidadania                                 150463,841500,0020,45800,00600,003000,00400,00...
DC            Democracia Cristã                         24592,5155664,001500,00200,0055664,0024592,514...
DEM           Democratas                                96000,0015000,00323,451250,005500,001250,00152...
MDB           Movimento Democrático Brasileiro          1000,00210000,001000,001000,001000,001000,0011...
NOVO          Partido Novo                              200,00100,00300,00240,00420,00120,00200,00100,...
PATRIOTA      Patriota                                  700,001000,001500,009,802270,951,0039,5514,001...
PC do B       Partido Comunista do Brasil               1000,00500,006000,0039000,00678,3010200,0045,5...
PCB           Partido Comunista Brasileiro                                                 1800,004157,40
PDT           Partido Democrático Trabalhista           100,00200000,00100000,0015000,0015000,00100000...
PL            Partido Liberal                           200,00200,00200,00200,00200,00200,00200,00200,...
PMB           Partido da Mulher Brasileira              3200,00600,00300,00500,00300,00300,00100000,00...
PMN           Partido da Mobilização Nacional           135,00285,004000,00238,09238,09132,50500,00500...
PODE          Podemos                                   500,00500,00500,00500,00500,00500,0030000,0010...
PP            PROGRESSISTAS                             482400,005002,7437,3010157,086771,39158400,003...
PROS          Partido Republicano da Ordem Social       15000,001250,00102212,0088781,00105000,0021991...
PRTB          Partido Renovador Trabalhista Brasileiro  0,50250,001000,001302,004100,005000,0023,7451,...
PSB           Partido Socialista Brasileiro             305000,00198190,8449,881500,00374323,545254,80...
PSC           Partido Social Cristão                    2000,001000,001500,001500,001000,00184,20184,6...
PSD           Partido Social Democrático                79,004900000,0079,004900000,0032,6515,001000,0...
PSDB          Partido da Social Democracia Brasileira   6720,00100780,0023572,00125164,0070336,0056204...
PSL           Partido Social Liberal                    3000,003000,00210000,00420000,00170000,0067000...
PSOL          Partido Socialismo e Liberdade            31814,2331814,2331814,2331814,2314172,3524744,...
PT            Partido dos Trabalhadores                 29000,0013000,0057000,0024000,00280,00280,0010...
PTB           Partido Trabalhista Brasileiro            70000,0095471,8980096,30320385,19158706,393967...
PTC           Partido Trabalhista Cristão               100000,001500,002000,004931,0019500,0030000,00...
PV            Partido Verde                             15000,008400,009000,006000,006000,003168,55530...
REDE          Rede Sustentabilidade                     855833,33460833,33750057,60511525,00421907,409...
REPUBLICANOS  REPUBLICANOS                              36,0018,6580000,0036,0080,0086,0029,10625,0062...
SOLIDARIEDADE Solidariedade                             35000,0060000,00210000,004000,005000,0090000,0...
UP            Unidade Popular                                                3000,002500,006700,003000,00

## Qual é o top 10?

Crie um novo dataframe com os 10 partidos com mais doações. Você precisa primeiro ordenar os resultados e depois selecionar apenas os 10 primeiros.

In [70]:
#Fórmula correta.

total_doacoes_decrescente = total_doacoes.sort_values(by='VR_RECEITA',ascending=False)
total_doacoes_decrescente

#Minha fórmula
#df_final[['NM_PARTIDO_DOADOR','VR_RECEITA']].groupby(by='VR_RECEITA').sum().sort_values(by=0,ascending=False).head()

                                                                                               VR_RECEITA
SG_PARTIDO    NM_PARTIDO
DEM           Democratas                                96000,0015000,00323,451250,005500,001250,00152...
REDE          Rede Sustentabilidade                     855833,33460833,33750057,60511525,00421907,409...
PSD           Partido Social Democrático                79,004900000,0079,004900000,0032,6515,001000,0...
PTB           Partido Trabalhista Brasileiro            70000,0095471,8980096,30320385,19158706,393967...
PATRIOTA      Patriota                                  700,001000,001500,009,802270,951,0039,5514,001...
PSDB          Partido da Social Democracia Brasileira   6720,00100780,0023572,00125164,0070336,0056204...
PODE          Podemos                                   500,00500,00500,00500,00500,00500,0030000,0010...
PP            PROGRESSISTAS                             482400,005002,7437,3010157,086771,39158400,003...
REPUBLICANOS  REPUBLICANOS                              36,0018,6580000,0036,0080,0086,0029,10625,0062...
SOLIDARIEDADE Solidariedade                             35000,0060000,00210000,004000,005000,0090000,0...
PMB           Partido da Mulher Brasileira              3200,00600,00300,00500,00300,00300,00100000,00...
PSOL          Partido Socialismo e Liberdade            31814,2331814,2331814,2331814,2314172,3524744,...
PSB           Partido Socialista Brasileiro             305000,00198190,8449,881500,00374323,545254,80...
PSL           Partido Social Liberal                    3000,003000,00210000,00420000,00170000,0067000...
UP            Unidade Popular                                                3000,002500,006700,003000,00
PT            Partido dos Trabalhadores                 29000,0013000,0057000,0024000,00280,00280,0010...
DC            Democracia Cristã                         24592,5155664,001500,00200,0055664,0024592,514...
PSC           Partido Social Cristão                    2000,001000,001500,001500,001000,00184,20184,6...
PL            Partido Liberal                           200,00200,00200,00200,00200,00200,00200,00200,...
NOVO          Partido Novo                              200,00100,00300,00240,00420,00120,00200,00100,...
PCB           Partido Comunista Brasileiro                                                 1800,004157,40
CIDADANIA     Cidadania                                 150463,841500,0020,45800,00600,003000,00400,00...
PV            Partido Verde                             15000,008400,009000,006000,006000,003168,55530...
AVANTE        AVANTE                                    15000,00500,00750,00750,00500,001,205000,00500...
PROS          Partido Republicano da Ordem Social       15000,001250,00102212,0088781,00105000,0021991...
PMN           Partido da Mobilização Nacional           135,00285,004000,00238,09238,09132,50500,00500...
PTC           Partido Trabalhista Cristão               100000,001500,002000,004931,0019500,0030000,00...
PC do B       Partido Comunista do Brasil               1000,00500,006000,0039000,00678,3010200,0045,5...
MDB           Movimento Democrático Brasileiro          1000,00210000,001000,001000,001000,001000,0011...
PDT           Partido Democrático Trabalhista           100,00200000,00100000,0015000,0015000,00100000...
PRTB          Partido Renovador Trabalhista Brasileiro  0,50250,001000,001302,004100,005000,0023,7451,...

# Vamos visualizar os resultados?
Na aula, nós vimos como usar o matplotlib para gerar gráficos. Agora, vamos descobrir uma nova forma de fazer o mesmo usando um método nativo Pandas. Experimente colocar `.plot(kind='barh')` após a consulta ou dataframe anterior.

Com este comando, podemos produzir um gráfico (plot) do tipo (kind) de barras horizontais (barh).

In [69]:
top_10 = total_doacoes_decrescente.head(10)
top_10

                                                                                              VR_RECEITA
SG_PARTIDO    NM_PARTIDO
DEM           Democratas                               96000,0015000,00323,451250,005500,001250,00152...
REDE          Rede Sustentabilidade                    855833,33460833,33750057,60511525,00421907,409...
PSD           Partido Social Democrático               79,004900000,0079,004900000,0032,6515,001000,0...
PTB           Partido Trabalhista Brasileiro           70000,0095471,8980096,30320385,19158706,393967...
PATRIOTA      Patriota                                 700,001000,001500,009,802270,951,0039,5514,001...
PSDB          Partido da Social Democracia Brasileira  6720,00100780,0023572,00125164,0070336,0056204...
PODE          Podemos                                  500,00500,00500,00500,00500,00500,0030000,0010...
PP            PROGRESSISTAS                            482400,005002,7437,3010157,086771,39158400,003...
REPUBLICANOS  REPUBLICANOS                             36,0018,6580000,0036,0080,0086,0029,10625,0062...
SOLIDARIEDADE Solidariedade                            35000,0060000,00210000,004000,005000,0090000,0...

In [73]:
top_10.sort_values(by='VR_RECEITA').plot(kind='barh', color={'red'})

TypeError: ignored

In [74]:
#Correção. Não fiz esse.

ultimos_10 = total_doacoes_decrescente.tail(10)
ultimos_10

                                                                                            VR_RECEITA
SG_PARTIDO NM_PARTIDO
CIDADANIA  Cidadania                                 150463,841500,0020,45800,00600,003000,00400,00...
PV         Partido Verde                             15000,008400,009000,006000,006000,003168,55530...
AVANTE     AVANTE                                    15000,00500,00750,00750,00500,001,205000,00500...
PROS       Partido Republicano da Ordem Social       15000,001250,00102212,0088781,00105000,0021991...
PMN        Partido da Mobilização Nacional           135,00285,004000,00238,09238,09132,50500,00500...
PTC        Partido Trabalhista Cristão               100000,001500,002000,004931,0019500,0030000,00...
PC do B    Partido Comunista do Brasil               1000,00500,006000,0039000,00678,3010200,0045,5...
MDB        Movimento Democrático Brasileiro          1000,00210000,001000,001000,001000,001000,0011...
PDT        Partido Democrático Trabalhista           100,00200000,00100000,0015000,0015000,00100000...
PRTB       Partido Renovador Trabalhista Brasileiro  0,50250,001000,001302,004100,005000,0023,7451,...

In [75]:
ultimos_10.plot(kind='barh')

TypeError: ignored

## Qual o valor médio das doações por tipo de doador?

Agora é sua vez! A partir dos comandos anteriores, faça uma nova consulta para descobrir a mediana de acordo com o tipo de doador.

In [21]:
df_final[['NM_PARTIDO_DOADOR', 'VR_RECEITA']].groupby(by='NM_PARTIDO_DOADOR').median()

<ipython-input-21-8f09d5a6d9e2>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_final[['NM_PARTIDO_DOADOR', 'VR_RECEITA']].groupby(by='NM_PARTIDO_DOADOR').median()

Empty DataFrame
Columns: []
Index: [AVANTE, Cidadania, Democracia Cristã, Democratas, Movimento Democrático Brasileiro, PROGRESSISTAS, Partido Comunista Brasileiro, Partido Comunista do Brasil, Partido Democrático Trabalhista, Partido Liberal, Partido Novo, Partido Renovador Trabalhista Brasileiro, Partido Republicano da Ordem Social, Partido Social Cristão, Partido Social Democrático, Partido Social Liberal, Partido Socialismo e Liberdade, Partido Socialista Brasileiro, Partido Trabalhista Brasileiro, Partido Trabalhista Cristão, Partido Verde, Partido da Mulher Brasileira, Partido da Social Democracia Brasileira, Partido dos Trabalhadores, Patriota, Podemos, REPUBLICANOS, Rede Sustentabilidade, Solidariedade, Unidade Popular]

## Qual o valor mais alto de doação por tipo de doador?

In [22]:
df_final[['NM_PARTIDO_DOADOR', 'VR_RECEITA']].groupby(by='NM_PARTIDO_DOADOR').max()

                                         VR_RECEITA
NM_PARTIDO_DOADOR
AVANTE                                        78,36
Cidadania                                   9000,00
Democracia Cristã                          94634,00
Democratas                                   986,00
Movimento Democrático Brasileiro              98,51
PROGRESSISTAS                                945,00
Partido Comunista Brasileiro                4157,40
Partido Comunista do Brasil                 8226,00
Partido Democrático Trabalhista                9,15
Partido Liberal                               95,00
Partido Novo                                 600,00
Partido Renovador Trabalhista Brasileiro    5000,00
Partido Republicano da Ordem Social        96000,00
Partido Social Cristão                        99,30
Partido Social Democrático                  9502,40
Partido Social Liberal                        98,23
Partido Socialismo e Liberdade             95031,26
Partido Socialista Brasileiro                936,73
Partido Trabalhista Brasileiro             95471,89
Partido Trabalhista Cristão                   54,15
Partido Verde                                 97,00
Partido da Mulher Brasileira              150000,00
Partido da Social Democracia Brasileira      960,00
Partido dos Trabalhadores                   9382,00
Patriota                                     970,00
Podemos                                   950000,00
REPUBLICANOS                              955503,79
Rede Sustentabilidade                     949975,00
Solidariedade                             910000,00
Unidade Popular                             6700,00

## Crie uma tabela com valor máximo, mínimo e a mediana, por estado e tipo de doador

In [76]:
df_final[['TIPO_DOADOR','SG_UF','VR_RECEITA']].groupby(by=['TIPO_DOADOR','SG_UF']).agg({'VR_RECEITA': ['min', 'median', 'max']})

TypeError: ignored

# Entreviste você mesmo

Escreva abaixo pelo menos outras três perguntas que podem ser feitas à base de dados. Escreva a pergunta como um comentário acima do código com a consulta em Python.