<a href="https://colab.research.google.com/github/camilacruz-cs/python-para-inovacao-civica/blob/main/Semana_1__Aula_Extra_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Programação do zero a prática: Primeiros passos com Python 🐍🎲🐼

####Aula Exta - Pandas

# Notebooks 💻
* O que são
* Como funcionam
* Mini tour pelos principais lugares
* Erros comuns:
 *    Congelar a célula
 *    Erro na célula

# Python, bem basiquinho 🐍
## Agenda
* O que é o Python
* Comentários
* Import
 *    Zen do Python
* Tipos de dados
 *    Type
 *    String
 *    Funções
 *    Números
* Booleanos
* Variável
* Método
* Função Print
* Coleção de dados
 *    Listas
 *    Dicionários
* For
* If e Else

In [1]:
#Várias bibliotecas já vem pré-instaladas no Python, sendo assim não é necessário a instalação, apenas a importação.
#Para se importar alguma biblioteca, se faz necessário o uso da palavra IMPORT.

#Zen do Python
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## Tipos de dados em Python
1. **Strings** - São letras e textos em Python. É importante que se esteja entre aspas simples ou duplas, e assim o Python irá entender.

In [2]:
'Olá, mundo!'

'Olá, mundo!'

In [3]:
'E ai, estou aprendo Python e estou animada <3'

'E ai, estou aprendo Python e estou animada <3'

In [4]:
#Concatenar

'Quinta' + ' - ' + 'Feira'

'Quinta - Feira'

In [6]:
#Métodos em Python - Ferramentas que podem ser usadas para facilitar nossos processos.

type('Oie')

str

In [ ]:
#Qual é a diferença?

In [8]:
'2' + '3'
#Resposta - Aqui, por estar entre aspas, o Python entenderá como texto.
#Logo, a resposta deverá ser 23.

'23'

In [9]:
2+3
#Resposta - Aqui, o Python entende cada número como um número e irá somar.
#Logo, resposta deverá ser 5.

5

## Tipos de dados em Python
2. **Números** - São divididos em duas categorias;

* Float - São números com vírgula, com casas decimais.
* Inteiros - Números sem casas decimais.

In [10]:
#Inteiros

type(21)

int

In [11]:
#Float

type(2.1)

float

### Operações matemáticas

In [12]:
#Soma

2  + 2

4

In [13]:
#Subtração

2 - 2

0

In [14]:
#Divisão

2/2

1.0

In [15]:
#Multiplicação

2*2

4

In [17]:
#Potência

2**2

4

In [19]:
#Qual é o resultado?

2+4/2

4.0

## Tipos de dados em Python
3. **Booleano** - São divididos em duas categorias;

* False

* Verdadeiro

In [20]:
type(False)

bool

In [21]:
type(True)

bool

###Variáveis

* De maneira fácil, variáveis são caixas que armazenam dados/valores.

* Com a variável definida, se consegue usar ela mais de uma vez durante o trabalho.

In [22]:
numero = 15

###Operadores Lógicos

In [23]:
#Diferente

numero != 15

False

In [24]:
#Comparação
numero == 34

False

In [25]:
#Maior que

2 > 4

False

In [26]:
#Menor que

2 < 4

True

In [27]:
#Maior igual

numero >= 8

True

In [28]:
#Menor igual

numero <=100

True

### Métodos

In [29]:
minha_fruta = 'acerola'

In [30]:
minha_fruta.upper()

'ACEROLA'

In [31]:
minha_fruta.lower()

'acerola'

In [32]:
minha_fruta.count('a')

2

In [34]:
bebida = 'agua gelada sem gás'
bebida

'agua gelada sem gás'

In [35]:
#Encadear vários métodos em sequência.

bebida.upper().split()

['AGUA', 'GELADA', 'SEM', 'GÁS']

### Print

In [36]:
print('Bom dia, e ai. Como que vai?')

Bom dia, e ai. Como que vai?

In [38]:
evento = 'coda2021'

print(evento)

coda2021

In [39]:
#Essa sintaxe é um pouco mais complexa, pois ela permite uma variável no meio do texto.
#O 'f' é o format.
print(f'bom dia, {evento}')

bom dia, coda2021

In [40]:
print(f'boa tarde, {numero}')

boa tarde, 15

In [41]:
print(f'boa tarde, {minha_fruta}')

boa tarde, acerola

## Aqui já iremos começar a pensar em estruturas de dados, que é de suma importância para análise de dados.

### Listas

* São uma sequência de variáveis que queremos guardar ou reservar.

* Toda contagem em listas começa no ZERO. Logo, [0, 1, 2...]

In [43]:
frutas = ['pera', 'uva', 'maça', 'laranja']

In [44]:
#Pegar o segundo elemento.
#Idexaçao no Python inicia no ZERO [0]

frutas[2]

'maça'

In [46]:
#Pegando o último elemento

frutas[3]

'laranja'

### Fatiamento de listas

* Pegando apenas trechos da lista.

In [47]:
frutas[0:2]

['pera', 'uva']

In [48]:
#Pegando a primeira
frutas[:1]

['pera']

In [49]:
#Tamanho de listas
len(frutas)

4

###Dicionário

* É uma lista mais 'avançada.
* Chave: par-valor

In [50]:
salada_de_frutas = {'ingredientes': frutas,
                    'preparo':'corte tudo e misture',
                    'tempo':60
                    }

In [51]:
#pegar um item
salada_de_frutas['ingredientes']

['pera', 'uva', 'maça', 'laranja']

In [52]:
#adicionar item
salada_de_frutas['porções'] = 7

In [53]:
#excluir item
del salada_de_frutas['tempo']

In [54]:
print(salada_de_frutas)

{'ingredientes': ['pera', 'uva', 'maça', 'laranja'], 'preparo': 'corte tudo e misture', 'porções': 7}

## Estrutura de repetição `For`

* É um looping.

In [55]:
#Iterando em listas

for frutas in frutas:
  print(frutas)

pera
uva
maça
laranja

In [56]:
#Pegar as chaves do dicionário

for chave in salada_de_frutas:
  print(salada_de_frutas[chave])

['pera', 'uva', 'maça', 'laranja']
corte tudo e misture
7

In [57]:
#Iterando dentro de um texto

for letra in evento:
  print(letra)

c
o
d
a
2
0
2
1

## Estrutura Condicional `if`

* Traz se é verdadeiro ou falso seu questionamento.

In [58]:
if 4 > 3:
  print('É maior sim')

É maior sim

In [59]:
if 4 > 7:
  print('É maior sim')
else:
  print('claro que nao é')

claro que nao é

In [60]:
idade = 21

if idade > 30:
  print('Sou adulto')
elif idade > 19 & idade <= 30:
  print('Sou jovem')
else:
  print('Sou adolescente')

Sou jovem

##Pandas 🐼🎲
* Importar o pandas
* Carga de dados
* Detalhando os dados
* Organizando os dados
* Filtrando os dados
* Agrupando e agregando
* Exportando

In [61]:
import pandas as pd

In [97]:
#Trazendo os dados para o projeto

df_empresas = pd.read_csv('/content/empresas_trabalho_escravo.csv')

### Detalhando o DF.

In [98]:
df_empresas.head(10)

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
0,2010,1,19/01/2010 a 29/01/2010,GO,MONTE ALEGRE DE GOIÁS,0151201,CRIAÇÃO DE BOVINOS P,THIAGO NEIVA HONORATO\n,330874152,FAZENDA JOÃO LUIZ,3
1,2010,1,19/01/2010 a 29/01/2010,GO,MONTE ALEGRE DE GOIÁS,0151201,CRIAÇÃO DE BOVINOS P,RENIUTON SOUZA DE MORAES\n,24845256134,FAZENDA OLHO D'ÁGUA,5
2,2010,1,19/01/2010 a 29/01/2010,TO,NATIVIDADE,0151201,CRIAÇÃO DE BOVINOS P,EMIVAL RAMOS CAIADO FILHO\n,9655298191,FAZENDA SANTA MÔNICA,26
3,2010,2,26/01/2010 a 05/02/2010,PA,MARABÁ,0151202,CRIAÇÃO DE BOVINOS P,HÉLIO DUARTE SOARES\n,4454931860,FAZENDA BOA SORTE,2
4,2010,3,27/01/2010 a 05/02/2010,PA,SANTA MARIA DAS BARREIRAS,0151201,CRIAÇÃO DE BOVINOS P,CSM AGROPECUÁRIA S.A\n(FAZENDA TARUMÃ),5303431000221,CSM AGROPECUÁRIA S.A\n(FAZENDA TARUMÃ),28
5,2010,4,23/12/2010 a 29/01/2010,MG,ARAGUARI,0119999,CULTIVO DE OUTRAS PL,PEDRO EUSTÁQUIO PELLEGRINI\n,35048328604,FAZENDA CUNHAS,14
6,2010,5,23/02/2010 a 05/03/2010,PA,CONCEIÇÃO DO ARAGUAIA,0151201,CRIAÇÃO DE BOVINOS P,ANTÔNIO MARTINS RIBEIRO\n,13521519104,FAZENDA SÃO PEDRO,4
7,2010,7,22/01/2010 a 18/02/2010,AC,PORTO ACRE,0151202,CRIAÇÃO DE BOVINOS P,ROQUE REIS BARREIROS JÚNIOR\n,33954305291,FAZENDA HARMONIA,8
8,2010,8,02/03/2010 a 08/03/2010,RO,PORTO VELHO,0151201,CRIAÇÃO DE BOVINOS P,JOÃO ALTAIR CAETANO DOS SANTOS\n,36841323904,FAZENDA RANCHO COLORADO,8
9,2010,9,03/03/2010 a 09/03/2010,RS,BOM JESUS,0119903,CULTIVO DE BATATA-IN,PAULO CEZAR SEGALA\n,73466778034,PAULO CEZAR SEGALA\n,24

In [66]:
#Pegando exemplos aleatórios dentro do DF.

df_empresas.sample()

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
621,2013,122,18/03/2013 a 08/08/2013,MG,CHÁCARA,4120400,CONSTRUÇÃO DE EDIFÍC,CONSTRUTORA SOUSZA E GUERRA BICAS LTDA,10224454000108,CONSTRUTORA SOUSZA E GUERRA BICAS LTDA,5

In [67]:
#Entrando um pouco em uma análise exploratória dos dados..
#Resumo estatístico

df_empresas.describe()

               Ano     Operação  CNPJ/CEI/CPF  Nº Trab. cond. analog escravo
count  1387.000000  1387.000000  1.387000e+03                    1387.000000
mean   2014.268926    77.988464  6.471429e+12                      13.744773
std       3.175335    49.190898  1.543392e+13                      26.791397
min    2010.000000     1.000000  9.889597e+06                       1.000000
25%    2011.000000    36.000000  1.608456e+10                       4.000000
50%    2014.000000    73.000000  5.550614e+10                       7.000000
75%    2017.000000   116.000000  5.626995e+12                      14.000000
max    2020.000000   261.000000  9.702967e+13                     433.000000

In [68]:
#Quantidade de linhas e colunas

df_empresas.shape

(1387, 11)

In [69]:
#Nome das colunas e seus respectivos tipos numéricos

df_empresas.dtypes

Ano                               int64
Operação                          int64
Dia/Mês                          object
UF                               object
Município                        object
CNAE                             object
Descrição CNAE                   object
Proprietário                     object
CNPJ/CEI/CPF                      int64
Estabelecimento Inspecionado     object
Nº Trab. cond. analog escravo     int64
dtype: object

In [71]:
#Nome das colunas que existem no DF

df_empresas.columns

Index(['Ano', 'Operação', 'Dia/Mês', 'UF', 'Município', 'CNAE',
       'Descrição CNAE', 'Proprietário', 'CNPJ/CEI/CPF',
       'Estabelecimento Inspecionado', 'Nº Trab. cond. analog escravo'],
      dtype='object')

###Organização dos Dados

In [72]:
#Ordenamento dos dados
#Sort_Values - Quer se ordenar por qual coluna?

df_empresas.sort_values('UF')

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
789,2014,145,18/11/2014 a 19/12/2014,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,FELIPE JOEL VERAS PINHEIRO,86784552253,ARRENDAMENTO DA FAZENDA ESTANCIA GUANABARA,15
685,2014,21,11/03/2014 a 21/03/2014,AC,SENA MADUREIRA,1092900,FABRICAÇÃO DE BISCOI,MIRAGINA S/A INDÚSTRIA E COMÉRCIO,4063681000198,FAZENDA MIRAGINA I,1
698,2014,33,29/07/2014 a 08/08/2014,AC,TARAUACÁ,0151201,CRIAÇÃO DE BOVINOS P,JOSÉ TELES DE OLIVEIRA FILHO,62069268268,FAZENDA PORTO ALEGRE,55
726,2014,67,22/04/2014 a 17/07/2014,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,AMANDIO CELESTINO COGO,12029939900,ARRENDAMENTO DA FAZENDA PERSEVERANÇA,3
921,2016,22,29/03/2016 a 08/04/2016,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,LEANDRO LUIS LEITE,9817623874,FAZENDA CORREGO DO OURO,7
...,...,...,...,...,...,...,...,...,...,...,...
399,2012,37,09/04/2012 a 27/04/2012,TO,DIANÓPOLIS,0220902,PRODUÇÃO DE CARVÃO V,CLÁUDIO ROBERTO MARTIN,4689364915,FAZENDA MORADA VERDE,9
400,2012,37,09/04/2012 a 27/04/2012,TO,PRESIDENTE KENNEDY,0220902,PRODUÇÃO DE CARVÃO V,CARVOARIA CARVÃO NATIVO LTDA,14227279000155,FAZENDA SÃO CRISTÓVÃO I,13
401,2012,37,09/04/2012 a 27/04/2012,TO,CRISTALÂNDIA,0220902,PRODUÇÃO DE CARVÃO V,SÉRGIO ANTÔNIO NASCIMENTO,19978294600,FAZENDA SCALA II,7
205,2011,38,02/02/2011 a 15/03/2011,TO,CONCEIÇÃO DO TOCANTINS,0210108,PRODUÇÃO DE CARVÃO V,GERALDO OTAVIANO MENDES -,90929829620,CARVOARIA TEIXEIRA,6
841,2015,74,17/11/2015 a 27/11/2015,TO,BERNARDO SAYÃO,0151201,CRIAÇÃO DE BOVINOS P,AGROPECUÁRIA TERRA GRANDE S/A,1432186000110,AGROPECUÁRIA TERRA GRANDE S/A,15

In [73]:
#Ordenando de uma maneira decrescente

df_empresas.sort_values('UF', ascending=False)

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
863,2015,103,16/07/2015 a 22/07/2015,TO,PORTO NACIONAL,0220902,PRODUÇÃO DE CARVÃO V,LUCIANO ROSA DO NASCIMENTO,51873702949,FAZENDA CASTELO,9
553,2013,43,21/05/2013 a 31/05/2013,TO,COLMÉIA,0151201,CRIAÇÃO DE BOVINOS P,PAULO VICENTE DA MOTA,23248823100,FAZENDA ESTAÇÃO,16
149,2010,125,30/11/2010 a 09/12/2010,TO,ARAGUACEMA,0151201,CRIAÇÃO DE BOVINOS P,NEWTON OLIVEIRA,2513595159,"FAZENDAS DA BEZERRA, PAU BRASIL, SÃO JOSÉ, GAR...",33
834,2015,62,02/10/2015 a 09/10/2015,TO,BABAÇULÂNDIA,0220901,EXTRAÇÃO DE MADEIRA,CERÂMICA CERMAR,3894214000147,FAZENDA PARAISO,2
686,2014,22,16/04/2014 a 30/04/2014,TO,NATIVIDADE,0151201,CRIAÇÃO DE BOVINOS P,FABIANO IAMAGUTI MAEDA E OUTROS,11912555816,FAZENDA ESPERANÇA,6
...,...,...,...,...,...,...,...,...,...,...,...
789,2014,145,18/11/2014 a 19/12/2014,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,FELIPE JOEL VERAS PINHEIRO,86784552253,ARRENDAMENTO DA FAZENDA ESTANCIA GUANABARA,15
337,2011,151,23/08/2011 a 22/11/2011,AC,FEIJÓ,0151201,CRIAÇÃO DE BOVINOS P,RUI PINTO,73757187768,FAZENDA MASSIPIRA,7
252,2011,69,11/05/2011 a 07/06/2011,AC,PLÁCIDO DE CASTRO,0151201,CRIAÇÃO DE BOVINOS P,FERNANDO BARBOSA TEIXEIRA -,61773930125,FAZENDA VALE VERDE,8
7,2010,7,22/01/2010 a 18/02/2010,AC,PORTO ACRE,0151202,CRIAÇÃO DE BOVINOS P,ROQUE REIS BARREIROS JÚNIOR\n,33954305291,FAZENDA HARMONIA,8
557,2013,47,12/04/2013 a 09/05/2013,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,MOZAR MARCONDES FILHO,33574090978,FAZENDA AGOPECUÁRIA SORRISO,13

In [75]:
#As 10 primeiras linhas

df_empresas.sort_values('UF').head(10)

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
789,2014,145,18/11/2014 a 19/12/2014,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,FELIPE JOEL VERAS PINHEIRO,86784552253,ARRENDAMENTO DA FAZENDA ESTANCIA GUANABARA,15
685,2014,21,11/03/2014 a 21/03/2014,AC,SENA MADUREIRA,1092900,FABRICAÇÃO DE BISCOI,MIRAGINA S/A INDÚSTRIA E COMÉRCIO,4063681000198,FAZENDA MIRAGINA I,1
698,2014,33,29/07/2014 a 08/08/2014,AC,TARAUACÁ,0151201,CRIAÇÃO DE BOVINOS P,JOSÉ TELES DE OLIVEIRA FILHO,62069268268,FAZENDA PORTO ALEGRE,55
726,2014,67,22/04/2014 a 17/07/2014,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,AMANDIO CELESTINO COGO,12029939900,ARRENDAMENTO DA FAZENDA PERSEVERANÇA,3
921,2016,22,29/03/2016 a 08/04/2016,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,LEANDRO LUIS LEITE,9817623874,FAZENDA CORREGO DO OURO,7
7,2010,7,22/01/2010 a 18/02/2010,AC,PORTO ACRE,0151202,CRIAÇÃO DE BOVINOS P,ROQUE REIS BARREIROS JÚNIOR\n,33954305291,FAZENDA HARMONIA,8
557,2013,47,12/04/2013 a 09/05/2013,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,MOZAR MARCONDES FILHO,33574090978,FAZENDA AGOPECUÁRIA SORRISO,13
337,2011,151,23/08/2011 a 22/11/2011,AC,FEIJÓ,0151201,CRIAÇÃO DE BOVINOS P,RUI PINTO,73757187768,FAZENDA MASSIPIRA,7
948,2016,63,16/08/2016 a 26/08/2016,AC,SENA MADUREIRA,0151201,CRIAÇÃO DE BOVINOS P,JOSE ARMANDO DE SOUZA,22753540691,FAZENDA ANTIMARY,10
252,2011,69,11/05/2011 a 07/06/2011,AC,PLÁCIDO DE CASTRO,0151201,CRIAÇÃO DE BOVINOS P,FERNANDO BARBOSA TEIXEIRA -,61773930125,FAZENDA VALE VERDE,8

In [76]:
#Ordenas por mais de uma coluna
df_empresas.sort_values(['UF','Ano'])

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
7,2010,7,22/01/2010 a 18/02/2010,AC,PORTO ACRE,0151202,CRIAÇÃO DE BOVINOS P,ROQUE REIS BARREIROS JÚNIOR\n,33954305291,FAZENDA HARMONIA,8
252,2011,69,11/05/2011 a 07/06/2011,AC,PLÁCIDO DE CASTRO,0151201,CRIAÇÃO DE BOVINOS P,FERNANDO BARBOSA TEIXEIRA -,61773930125,FAZENDA VALE VERDE,8
337,2011,151,23/08/2011 a 22/11/2011,AC,FEIJÓ,0151201,CRIAÇÃO DE BOVINOS P,RUI PINTO,73757187768,FAZENDA MASSIPIRA,7
557,2013,47,12/04/2013 a 09/05/2013,AC,RIO BRANCO,0151201,CRIAÇÃO DE BOVINOS P,MOZAR MARCONDES FILHO,33574090978,FAZENDA AGOPECUÁRIA SORRISO,13
685,2014,21,11/03/2014 a 21/03/2014,AC,SENA MADUREIRA,1092900,FABRICAÇÃO DE BISCOI,MIRAGINA S/A INDÚSTRIA E COMÉRCIO,4063681000198,FAZENDA MIRAGINA I,1
...,...,...,...,...,...,...,...,...,...,...,...
1007,2017,24,28/03/2017 a 07/04/2017,TO,ARAPOEMA,0151201,CRIAÇÃO DE BOVINOS P,JOAQUIM HENRIQUE ELIAS SOARES,74476009620,FAZENDA PONTAL,7
1033,2017,73,01/08/2017 a 11/08/2017,TO,ARAGUATINS,0151203,"CRIAÇÃO DE BOVINOS,",OSEMAR CRUZ MOUZINHO,62634119100,"FAZENDAS SENHOR DO BONFIM, CASA VERDE E ROQUINHO",8
1123,2018,83,09/10/2018 a 19/10/2018,TO,SANTA RITA DO TOCANTINS,0220902,PRODUÇÃO DE CARVÃO V,D M DE FREITAS - CARVÃO,16804341000150,FAZENDA SÃO SEBASTIÃO - LOT DUERE S/N - ZONA R...,9
1205,2019,34,21/06/2019 a 23/07/2019,TO,BERNARDO SAYÃO,0151201,CRIAÇÃO DE BOVINOS P,JOSÉ ROSA JÚNIOR,37760980159,"FAZENDA MACEDÔNIA I - RODOVIA TO-430, BERNARDO...",4
1343,2020,69,15/09/2020 a 25/09/2020,TO,NOVA OLINDA,0151201,CRIAÇÃO DE BOVINOS P,AUGUSTO GRATÃO,1592742149,FAZENDA GRATÃO,5

##Filtrando os Dados

In [77]:
#Olhando para apenas uma coluna.
df_empresas.UF

0       GO
1       GO
2       TO
3       PA
4       PA
        ..
1382    MG
1383    PA
1384    PA
1385    PI
1386    MS
Name: UF, Length: 1387, dtype: object

In [82]:
df_empresas['Município']

0           MONTE ALEGRE DE GOIÁS
1           MONTE ALEGRE DE GOIÁS
2                      NATIVIDADE
3                          MARABÁ
4       SANTA MARIA DAS BARREIRAS
                  ...
1382                MONTES CLAROS
1383               RONDON DO PARÁ
1384               RONDON DO PARÁ
1385                     PARNAÍBA
1386                      NIOAQUE
Name: Município, Length: 1387, dtype: object

In [78]:
#Neste caso, o nome desta coluna tem espaços e do jeito do exemplo anterior daria erros.
df_empresas['Nº Trab. cond. analog escravo']

0        3
1        5
2       26
3        2
4       28
        ..
1382     2
1383     8
1384    13
1385     1
1386    15
Name: Nº Trab. cond. analog escravo, Length: 1387, dtype: int64

In [86]:
#UNIQUE são todos os valores distintos.

df_empresas['Descrição CNAE'].unique()

array(['CRIAÇÃO DE BOVINOS P', 'CULTIVO DE OUTRAS PL',
       'CULTIVO DE BATATA-IN', 'EXTRAÇÃO DE MADEIRA ',
       'PRODUÇÃO DE CARVÃO V', 'CULTIVO DE CANA-DE-A', 'CULTIVO DE MAÇÃ',
       'CULTIVO DE SOJA', 'CULTIVO DE PINUS', 'CULTIVO DE CACAU',
       'CONSTRUÇÃO DE EDIFÍC', 'ATIVIDADES DE APOIO ', 'CULTIVO DE CAFÉ',
       'CULTIVO DE ERVA-MATE', 'FABRICAÇÃO DE ARTEFA',
       'PRODUÇÃO DE SEMENTES', 'CRIAÇÃO DE BOVINOS, ',
       'CONSTRUÇÃO DE RODOVI', 'EXTRAÇÃO DE AREIA, C',
       'CULTIVO DE MORANGO', 'OBRAS DE TERRAPLENAG',
       'EXTRAÇÃO DE MINÉRIOS', 'EXTRAÇÃO DE CALCÁRIO',
       'SERRARIAS COM DESDOB', 'CULTIVO DE FEIJÃO',
       'EXTRAÇÃO DE MINÉRIO ', 'CULTIVO DE MILHO', 'SERVIÇOS DE ENGENHAR',
       'DISCOTECAS, DANCETER', 'TRANSPORTE FERROVIÁR',
       'SERRARIAS SEM DESDOB', 'SERVIÇO DE PREPARAÇÃ',
       'CONFECÇÃO DE PEÇAS D', 'CULTIVO DE ARROZ', 'CULTIVO DE FUMO',
       'CULTIVO DE ABACAXI', 'CULTIVO DE SERINGUEI',
       'COMÉRCIO VAREJISTA D', 'HOTÉIS', 'CULTIVO DE EUCALIPTO',
       'INCORPORAÇÃO DE EMPR', 'FABRICAÇÃO DE MADEIR',
       'CULTIVO DE ESPÉCIES ', 'RESTAURANTES E SIMIL',
       'COMERCIO VAREJISTA D', 'CULTIVO DE AÇAÍ', 'FABRICAÇÃO DE PRODUT',
       'EXTRAÇÃO DE QUARTZO', 'EXTRAÇÃO E BRITAMENT',
       'MANUTENÇÃO DE REDES ', 'CONSTRUÇÃO DE ESTAÇÕ', 'FLORICULTURA',
       'CULTIVO DE COCO-DA-B', 'COMÉRCIO ATACADISTA ',
       'MOAGEM E FABRICAÇÃO ', 'PRODUÇÃO DE CASCA DE',
       'OBRAS DE URBANIZAÇÃO', 'TRANSPORTE RODOVIÁRI',
       'CULTIVO DE FRUTAS DE', 'CRIAÇÃO DE SUÍNOS',
       'EXTRAÇÃO DE CARVÃO M', 'OUTRAS OBRAS DE ENGE',
       'OUTRAS ATIVIDADES DE', 'PRODUÇÃO DE PRODUTOS',
       'FABRICAÇÃO DE ESTRUT', 'FABRICAÇÃO DE CONSER',
       'PRODUÇÃO DE FERRO-GU', 'CULTIVO DE TOMATE RA',
       'EXTRAÇÃO DE GRANITO ', 'COMPRA E VENDA DE IM',
       'COLETA DE RESÍDUOS N', 'CARGA E DESCARGA', 'CULTIVO DE DENDÊ',
       'CRIAÇÃO DE OUTROS AN', 'FABRICAÇÃO DE ÁLCOOL',
       'CULTIVO DE LARANJA', 'COLETA DE PRODUTOS N',
       'ATIVIDADES DE TRANSP', 'ATIVIDADES DE ASSOCI',
       'HORTICULTURA, EXCETO', 'CULTIVO DE OUTRAS OL',
       'OBRAS DE ALVENARIA', 'PESCA DE PEIXES EM Á',
       'FABRICAÇÃO DE AÇÚCAR', 'CULTIVO DE TECA', 'REFINO E OUTROS TRAT',
       'HOLDINGS DE INSTITUI', 'CULTIVO DE MANDIOCA',
       'OBRAS DE ACABAMENTO ', 'INSTALAÇÃO DE PORTAS',
       'FACÇÃO DE PEÇAS DO V', 'SERVIÇOS DE ENTREGA ',
       'CRIAÇÃO DE FRANGOS P', 'SERVIÇOS DE CONFECÇÃ',
       'INSTALAÇÃO E MANUTEN', 'CULTIVO DE BANANA',
       'SERVIÇOS ESPECIALIZA', 'EXTRAÇÃO DE BASALTO ',
       'MONTAGEM DE ESTRUTUR', 'FABRICAÇÃO DE OBRAS ',
       'LANCHONETES, CASAS D', 'TRANSPORTE MARÍTIMO ',
       'FABRICAÇÃO DE BISCOI', 'COLETA DE CASTANHA-D',
       'OBRAS DE MONTAGEM IN', 'EXTRAÇÃO DE OUTROS M', 'CULTIVO DE MANGA',
       'CULTIVO DE MARACUJÁ', 'OUTRAS OBRAS DE ACAB',
       'CLUBES SOCIAIS, ESPO', 'PREPARAÇÃO E FIAÇÃO ',
       'FABRICAÇÃO DE OUTROS', 'PROCESSAMENTO INDUST',
       'CULTIVO DE CEBOLA', 'REPRESENTANTES COMER',
       'EXTRAÇÃO DE SAL MARI', 'TOALHEIROS', 'ABATE DE AVES',
       'ARMAZÉNS GERAIS - EM', 'CONFECÇÃO, SOB MEDID',
       'FILMAGEM DE FESTAS E', 'FABRICAÇÃO DE CIMENT',
       'CONFECÇÃO DE ROUPAS ', 'CONSTRUÇÃO DE REDES ',
       'FABRICAÇÃO DE BIJUTE', 'OUTROS ALOJAMENTOS N',
       'CRIAÇÃO DE EQÜINOS', 'INSTALAÇÕES HIDRÁULI',
       'PRODUÇÃO DE ESPETÁCU', 'PRODUÇÃO DE OVOS', 'FABRICAÇÃO DE OUTRAS',
       'COLETA DE PALMITO EM', 'SERVIÇOS DOMÉSTICOS',
       'ALUGUEL DE PALCOS, C', 'PREPARAÇÃO DE DOCUME',
       'ATIVIDADES DE CONSUL', 'ALUGUEL DE IMÓVEIS P',
       'FABRICAÇÃO DE FARINH', 'PREPARAÇÃO DE CANTEI',
       'ALUGUEL DE OUTRAS MÁ', 'CULTIVO DE OUTROS CE',
       'FABRICAÇÃO DE MÓVEIS', 'FABRICAÇÃO DE ÓLEOS ',
       'PARQUES DE DIVERSÃO ', 'EXTRAÇÃO DE GESSO E ',
       'BENEFICIAMENTO DE GE', 'FABRICAÇÃO DE MATERI',
       'EXTRAÇÃO DE SAIBRO E', 'SERVIÇOS AMBULANTES ', nan,
       'CRIAÇÃO DE OUTROS GA', 'MOTÉIS', 'EXTRAÇÃO DE GEMAS (P',
       'PERFURAÇÃO E CONSTRU', 'CULTIVO DE MUDAS EM '], dtype=object)

In [89]:

#Contar valores
df_empresas['Município'].value_counts()

SÃO PAULO                   53
RIO DE JANEIRO              33
SÃO FÉLIX DO XINGU          30
NOVO REPARTIMENTO           17
BELO HORIZONTE              16
                            ..
SANTA TEREZINHA              1
MATÃO                        1
SÃO PEDRO DA ÁGUA BRANCA     1
MATUPÁ                       1
NIOAQUE                      1
Name: Município, Length: 659, dtype: int64

In [90]:
#Contar valores
df_empresas['Descrição CNAE'].value_counts()

CRIAÇÃO DE BOVINOS P    357
PRODUÇÃO DE CARVÃO V    147
CONSTRUÇÃO DE EDIFÍC     90
CULTIVO DE CAFÉ          79
EXTRAÇÃO DE MADEIRA      72
                       ...
SERVIÇOS DE ENTREGA       1
INSTALAÇÃO DE PORTAS      1
OBRAS DE ACABAMENTO       1
REFINO E OUTROS TRAT      1
CULTIVO DE MUDAS EM       1
Name: Descrição CNAE, Length: 154, dtype: int64

## Para colunas numérias:

`min()` pega o menor valor;

`max()` pega o maior valor;

`median()` pega a mediana;

`mean()` pega a média;

`mode()` pega o valor mais comum

In [91]:
df_empresas['Nº Trab. cond. analog escravo'].max()

433

In [92]:
#Aqui é onde apenas a condição da UF ser igual a PE é verdadeira.

df_empresas[df_empresas.UF == 'PE']

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
494,2012,122,28/03/2012 a 23/11/2012,PE,ÁGUA PRETA,0113000,CULTIVO DE CANA-DE-A,MARCO ANTONIO MOURA DE ARRUDA FALCÃO,53156781487,ENGENHO CORRIENTE,19
512,2012,142,13/02/2012 a 19/03/2012,PE,RECIFE,6462000,HOLDINGS DE INSTITUI,RIOMAR SHOPPING S.A,8853970000141,RIOMAR SHOPPING S.A,6
528,2013,19,14/02/2013 a 04/03/2013,PE,PETROLINA,4330403,OBRAS DE ACABAMENTO,GESSO BRASIL LTDA ME,11340292000128,GESSO BRASIL LTDA ME,1
530,2013,21,04/03/2013 a 12/03/2013,PE,TORITAMA,1412601,CONFECÇÃO DE PEÇAS D,DILMA FIGUEREDO DA SILVA - ME,6005121000102,MOD'GRRIFF,7
725,2014,65,26/06/2014 a 02/07/2014,PE,PETROLINA,0133410,CULTIVO DE MANGA,MANDACARU AGROPECUÁRIA LTDA - EPP,10613545000127,FAZENDA MANDACARU,8
1198,2019,24,21/05/2019 a 31/05/2019,PE,ARARIPINA,1063500,FABRICAÇÃO DE FARINH,JOSÉ PEDRO DA SILVA,63333783304,"CASA DE FARINHA SÃO PEDRO, RUA ATRAS DA RUA 06...",5
1218,2019,48,09/04/2019 a 30/05/2019,PE,ARCOVERDE,0119999,CULTIVO DE OUTRAS PL,EDSON PORFIRIO DE CARVALHO,50791532453,"FAZENDA MALHADA - RODOVIA BR 232, KM 262/264, ...",10
1286,2019,159,28/08/2019 a 16/03/2020,PE,ARAÇOIABA,1071600,FABRICAÇÃO DE AÇÚCAR,USINA SAO JOSE S/A,10362820000187,ENGENHO CUMBE DE CIMA,45
1288,2019,162,28/08/2019 a 07/05/2020,PE,ARAÇOIABA,0113000,CULTIVO DE CANA-DE-A,USINA SÃO JOSÉ SA,10362820000187,"ENGENHO CUMBE DE CIMA, SITUADO NA ZONA RURAL, DO",45
1301,2020,2,27/01/2020 a 07/02/2020,PE,OLINDA,4120400,CONSTRUÇÃO DE EDIFÍC,CONSTRUTORA INGAZEIRA LTDA,749205000174,"OBRA LOCALIZADA NA AVENIDA BEIRA RIO, BAIRRO D...",10

## Filtro de Linha

In [93]:
df_empresas[df_empresas['Nº Trab. cond. analog escravo'] > 10]

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
2,2010,1,19/01/2010 a 29/01/2010,TO,NATIVIDADE,0151201,CRIAÇÃO DE BOVINOS P,EMIVAL RAMOS CAIADO FILHO\n,9655298191,FAZENDA SANTA MÔNICA,26
4,2010,3,27/01/2010 a 05/02/2010,PA,SANTA MARIA DAS BARREIRAS,0151201,CRIAÇÃO DE BOVINOS P,CSM AGROPECUÁRIA S.A\n(FAZENDA TARUMÃ),5303431000221,CSM AGROPECUÁRIA S.A\n(FAZENDA TARUMÃ),28
5,2010,4,23/12/2010 a 29/01/2010,MG,ARAGUARI,0119999,CULTIVO DE OUTRAS PL,PEDRO EUSTÁQUIO PELLEGRINI\n,35048328604,FAZENDA CUNHAS,14
9,2010,9,03/03/2010 a 09/03/2010,RS,BOM JESUS,0119903,CULTIVO DE BATATA-IN,PAULO CEZAR SEGALA\n,73466778034,PAULO CEZAR SEGALA\n,24
13,2010,11,10/03/2010 a 19/03/2010,PA,RONDON DO PARÁ,0210108,PRODUÇÃO DE CARVÃO V,CARVOARIA CHAPADÃO LTDA.,11007755000134,CARVOARIA CHAPADÃO LTDA.,61
...,...,...,...,...,...,...,...,...,...,...,...
1371,2020,170,08/10/2020 a 11/01/2021,MG,ARAXÁ,4292802,OBRAS DE MONTAGEM IN,MANSERV MONTAGEM E MANUTENÇÃO S/A,54183587000221,NaN,63
1372,2020,172,01/09/2020 a 12/01/2021,SC,ITUPORANGA,0119-9/04,NaN,PATRÍCIA POLICARPO,93566670987,NaN,14
1377,2020,180,02/09/2020 a 11/01/2021,PI,PIRACURUCA,0220999,COLETA DE PRODUTOS N,NILO FELIX CARDOSO,30625173368,NaN,19
1384,2020,189,01/12/2020 a 12/01/2021,PA,RONDON DO PARÁ,4671100,COMÉRCIO ATACADISTA,GUAMA COMÉRCIO DE COMPENSADOS E REPRESENTAÇÕES...,8724077000205,"FAZENDA MOREIRA, 4º31’16.4’’S – 48º15’03.2’’W,...",13
1386,2020,195,03/12/2020 a 13/01/2021,MS,NIOAQUE,0115600,CULTIVO DE SOJA,MAISA RODRIGUES DA COSTA,1385847107,FAZENDA SALTO,15

In [94]:
df_empresas[df_empresas.Ano > 2017]

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
1075,2018,3,16/01/2018 a 26/01/2018,PA,SÃO GERALDO DO ARAGUAIA,0151201,CRIAÇÃO DE BOVINOS P,SEBASTIÃO MARQUES DA MOTA,8148449104,"FAZENDAS PEDRA BRANCA, ARCO VERDE E TALISMÃ",5
1076,2018,6,29/01/2018 a 03/02/2018,GO,SÃO MIGUEL DO ARAGUAIA,0151201,CRIAÇÃO DE BOVINOS P,JOSÉ EDUARDO SANCHES,14277580858,FAZENDAS ALAIA E SANTA ADELAIDE,15
1077,2018,8,01/02/2018 a 22/02/2018,ES,ALFREDO CHAVES,0133402,CULTIVO DE BANANA,ANDRISSÃO ROQUE QUINTINO,7085262761,"SITIO BOM RETIRO, BOM RETIRO, DISTRITO DE IBIT...",6
1078,2018,9,25/01/2018 a 19/03/2018,GO,COLINAS DO SUL,0810006,"EXTRAÇÃO DE AREIA, C",RUI MATHILDES DOS REIS E LUIZ SÉRGIO MIRANDA L...,19977623000147,RMR - MECAL CONSTRUÇÕES E LOCAÇÕES DE MÁQUINAS...,5
1079,2018,10,22/01/2018 a 28/03/2018,MG,BELO HORIZONTE,4120400,CONSTRUÇÃO DE EDIFÍC,SAMARTE ENGENHARIA - CONSTRUÇÕES E INCORPORAÇÕ...,21317426000143,SAMARTE ENGENHARIA - CONSTRUÇÕES E INCORPORAÇÕ...,5
...,...,...,...,...,...,...,...,...,...,...,...
1382,2020,188,05/10/2020 a 12/01/2021,MG,MONTES CLAROS,0810006,"EXTRAÇÃO DE AREIA, C",GILSON APARECIDO LIRA,6964476814,"AVENIDA CENTRAL, Nº 222",2
1383,2020,189,01/12/2020 a 12/01/2021,PA,RONDON DO PARÁ,4211101,CONSTRUÇÃO DE RODOVI,CONSTRUTORA CAMILLO E EMPREENDIMENTOS LTDA,11022498000100,"FAZENDA MOREIRA, SITUADA EM COORDENADA GEOGRÁFICA",8
1384,2020,189,01/12/2020 a 12/01/2021,PA,RONDON DO PARÁ,4671100,COMÉRCIO ATACADISTA,GUAMA COMÉRCIO DE COMPENSADOS E REPRESENTAÇÕES...,8724077000205,"FAZENDA MOREIRA, 4º31’16.4’’S – 48º15’03.2’’W,...",13
1385,2020,190,26/11/2020 a 15/12/2020,PI,PARNAÍBA,1529700,FABRICAÇÃO DE ARTEFA,NR N SANTOS ME,63346605000159,CASA DOS COUROS,1
1386,2020,195,03/12/2020 a 13/01/2021,MS,NIOAQUE,0115600,CULTIVO DE SOJA,MAISA RODRIGUES DA COSTA,1385847107,FAZENDA SALTO,15

In [95]:
#Filtros compostos

acima_dez_libertos = df_empresas[df_empresas['Nº Trab. cond. analog escravo'] > 10]

acima_dez_libertos[df_empresas.Ano > 2017].head()

<ipython-input-95-c48873cb7c3c>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  acima_dez_libertos[df_empresas.Ano > 2017].head()

,Ano,Operação,Dia/Mês,UF,Município,CNAE,Descrição CNAE,Proprietário,CNPJ/CEI/CPF,Estabelecimento Inspecionado,Nº Trab. cond. analog escravo
1076,2018,6,29/01/2018 a 03/02/2018,GO,SÃO MIGUEL DO ARAGUAIA,0151201,CRIAÇÃO DE BOVINOS P,JOSÉ EDUARDO SANCHES,14277580858,FAZENDAS ALAIA E SANTA ADELAIDE,15
1084,2018,16,05/02/2018 a 18/04/2018,MG,SÃO VICENTE DE MINAS,7020400,ATIVIDADES DE CONSUL,"CÍCERO VICENTE DE ARAÚJO, MIGUEL DONISETE GONÇ...",11626418000125,NOVA VISÃO ASSESSORIA E CONSULTORIA EMPRESARIAL,132
1085,2018,16,05/02/2018 a 18/04/2018,MG,SÃO VICENTE DE MINAS,0151201,CRIAÇÃO DE BOVINOS P,NOVA VISÃO ASSESSORIA E CONSULTORIA EMPRESARIAL,11626418000125,OPERAÇÃO NOVA CANAÃ,433
1086,2018,20,23/07/2018 a 03/08/2018,MA,CAXIAS,0220999,COLETA DE PRODUTOS N,RAIMUNDO DE OLIVEIRA NOGUEIRA,27511529372,RAIMUNDO DE OLIVEIRA NOGUEIRA,20
1090,2018,27,22/03/2018 a 13/04/2018,MG,SÃO JOÃO DEL REI,0210108,PRODUÇÃO DE CARVÃO V,EDUARDO ABREU SILVA,3075549614,FAZENDA SULAIZ,15

## Agrupar e agregar dados

In [99]:
df_empresas.groupby('Ano')

In [104]:
df_empresas.groupby('Ano').sum()

<ipython-input-104-12181db4a2ba>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_empresas.groupby('Ano').sum()

      Operação      CNPJ/CEI/CPF  Nº Trab. cond. analog escravo
Ano
2010     10154  1040533081000965                           2640
2011     14893  1065494547474719                           2496
2012     10558   944432500457519                           2775
2013     13431  1466077410472069                           2808
2014     10446  1021003436487168                           1754
2015      8748   640933496658111                           1205
2016      6538   673443503759778                            972
2017      6653   397391511965390                            648
2018      8794   368787256184814                           1752
2019     10327   907281028163963                           1193
2020      7628   450493791395519                            821

In [105]:
df_empresas[['Ano','Nº Trab. cond. analog escravo']].groupby('Ano').sum().sort_values('Nº Trab. cond. analog escravo', ascending=False)

      Nº Trab. cond. analog escravo
Ano
2013                           2808
2012                           2775
2010                           2640
2011                           2496
2014                           1754
2018                           1752
2015                           1205
2019                           1193
2016                            972
2020                            821
2017                            648

## Bora Investigar? 🔎🕵🏾‍♀️

In [106]:
#Total de pessoas  libertas do trabalho escravo de 2010 a 2020
df_empresas['Nº Trab. cond. analog escravo'].sum()

19064

In [107]:
#rancking de empresas (CNAE)
df_empresas['Descrição CNAE'].value_counts().head(5)

CRIAÇÃO DE BOVINOS P    357
PRODUÇÃO DE CARVÃO V    147
CONSTRUÇÃO DE EDIFÍC     90
CULTIVO DE CAFÉ          79
EXTRAÇÃO DE MADEIRA      72
Name: Descrição CNAE, dtype: int64

In [108]:
#10 estados com mais operações

df_empresas[['UF','Operação']].groupby('UF').sum().sort_values('Operação', ascending=False).head(10)

    Operação
UF
MG     19173
PA     14810
SP     10773
GO      6598
BA      6450
RJ      6095
MT      5993
MA      4920
TO      4330
PI      4112

In [109]:
#Ano em que mais houve altuação

df_empresas[['Ano','Operação']].groupby('Ano').sum().sort_values('Operação', ascending=False)

      Operação
Ano
2011     14893
2013     13431
2012     10558
2014     10446
2019     10327
2010     10154
2018      8794
2015      8748
2020      7628
2017      6653
2016      6538

In [110]:
#Numero total de pessoas libertas através dos anos por estado

df_empresas[['UF','Nº Trab. cond. analog escravo']].groupby('UF').sum().sort_values('Nº Trab. cond. analog escravo', ascending=False)

    Nº Trab. cond. analog escravo
UF
MG                           5505
PA                           2091
SP                           1600
GO                           1448
TO                            790
MA                            776
MS                            770
BA                            767
PI                            678
SC                            633
RJ                            605
MT                            569
PR                            538
AM                            351
ES                            348
CE                            289
RO                            249
RS                            215
AL                            184
DF                            158
PE                            156
AC                            127
PB                             72
RR                             65
RN                             43
AP                             37

In [111]:
#Qual ano que mais houveram pessoas libertadas

df_empresas[['Ano','Nº Trab. cond. analog escravo']].groupby('Ano').sum().sort_values('Nº Trab. cond. analog escravo', ascending=False)

      Nº Trab. cond. analog escravo
Ano
2013                           2808
2012                           2775
2010                           2640
2011                           2496
2014                           1754
2018                           1752
2015                           1205
2019                           1193
2016                            972
2020                            821
2017                            648

#Salvando todo o trabalho feito <3

In [112]:
df_empresas.to_csv('Semana_1_Aula_Extra_Pandas.csv', index=False)